"""add_contractor_tables

Revision ID: 47be294e6179
Revises: 
Create Date: 2026-05-20 01:10:12.520379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47be294e6179'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_groups',
    sa.Column('contractor_group_id', sa.String(length=36), nullable=False),
    sa.Column('contractor_id', sa.String(length=36), nullable=False),
    sa.Column('technician_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contractor_group_id')
    )
    op.create_index(op.f('ix_contractor_groups_contractor_group_id'), 'contractor_groups', ['contractor_group_id'], unique=False)
    op.create_index(op.f('ix_contractor_groups_contractor_id'), 'contractor_groups', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_groups_technician_id'), 'contractor_groups', ['technician_id'], unique=False)
    op.create_table('job_assignments',
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('contractor_id', sa.String(length=36), nullable=False),
    sa.Column('technician_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_job_assignments_assignment_id'), 'job_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_contractor_id'), 'job_assignments', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_job_id'), 'job_assignments', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_assignments_technician_id'), 'job_assignments', ['technician_id'], unique=False)
    op.alter_column('jobs', 'latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('jobs', 'longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ft_jobs_search', table_name='jobs', mysql_prefix='FULLTEXT')
    op.drop_index('ix_users_location', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_location', 'users', ['latitude', 'longitude'], unique=False)
    op.create_index('ft_jobs_search', 'jobs', ['title', 'description'], unique=False, mysql_prefix='FULLTEXT')
    op.alter_column('jobs', 'longitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('jobs', 'latitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_job_assignments_technician_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_job_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_contractor_id'), table_name='job_assignments')
    op.drop_index(op.f('ix_job_assignments_assignment_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    op.drop_index(op.f('ix_contractor_groups_technician_id'), table_name='contractor_groups')
    op.drop_index(op.f('ix_contractor_groups_contractor_id'), table_name='contractor_groups')
    op.drop_index(op.f('ix_contractor_groups_contractor_group_id'), table_name='contractor_groups')
    op.drop_table('contractor_groups')
    # ### end Alembic commands ###
